variables:
  # gitlab ci debug
  CI_DEBUG_TRACE: "true"
  # gitlab ci environment weirdness (HOME isn't set or something)s
  TMPDIR: /home/gitlab-runner/cache
  NIX_INSTALLER_EXTRA_CONF: "/home/gitlab-runner/cache/flakehub-extra-conf"
  NIX_INSTALLER_NETRC: "/home/gitlab-runner/cache/nix-netrc"

  ## FLAKEHUB_PUSH_HOST is the api endpoint flakehub-push will push to
  # FLAKEHUB_PUSH_HOST: "https://api.flakehub.com" # prod
  FLAKEHUB_PUSH_HOST: "https://api.colemick.dev.f.second.systems" # tube

  ## FLAKEHUB_WEB_ENDPOINT is the endpoint clients will use to fetch flakehub-hosted flake closures 
  # FLAKEHUB_WEB_ENDPOINT: "https://flakehub.com" # prod
  FLAKEHUB_WEB_ENDPOINT: "https://web.colemick.dev.f.second.systems" # dev

  # FLAKEHUB_PUSH_BINARY_URL is where we acquire the `flakehub-push` binary
  # prod:
  # FLAKEHUB_PUSH_BINARY_URL: "https://install.determinate.systems/flakehub-push/branch/main/X64-Linux?ci=gitlab"
  # wip/dev:
  FLAKEHUB_PUSH_BINARY_URL: "https://install.determinate.systems/flakehub-push/pr/121/X64-Linux?ci=gitlab"
  # test from colemickens's machine
  # FLAKEHUB_PUSH_BINARY_URL: "https://web.colemick.dev.f.second.systems/flakehub-push"

super-cool-nix-job:
  id_tokens:
    GITLAB_JWT_ID_TOKEN:
      # aud: "api.flakehub.com"
      aud: "flakehub-localhost"
  script:
  - mkdir -p "${TMPDIR}"

  # pre-login with netrc
  - echo "machine ${FLAKEHUB_WEB_ENDPOINT} login flakehub password ${GITLAB_JWT_ID_TOKEN}" >> "${NIX_INSTALLER_NETRC}"
  - echo "machine ${FLAKEHUB_API_ENDPOINT} login flakehub password ${GITLAB_JWT_ID_TOKEN}" >> "${NIX_INSTALLER_NETRC}"
  - echo "netrc-file = ${NIX_INSTALLER_NETRC}" > "${NIX_INSTALLER_EXTRA_CONF}"

  # install-nix:
  - curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install linux --no-confirm --init none
  - . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

  # sanity check
  - cat "/etc/nix/nix.conf"
  - cat "${NIX_INSTALLER_NETRC}"

  # acquire flakehub-push
  - curl --output "${TMPDIR}/flakehub-push" --proto '=https' --tlsv1.2 -sSf -L "${FLAKEHUB_PUSH_BINARY_URL}"
  - chmod +x "${TMPDIR}/flakehub-push"

  # test pulling public+private flakes
  # - nix build -j0 "${FLAKEHUB_WEB_ENDPOINT}/f/ghuser-cole/flakesrock-public/0.3.1.tar.gz#truth"
  # - nix build -j0 "${FLAKEHUB_WEB_ENDPOINT}/f/ghuser-cole/flakesrock-public/*.tar.gz#truth"
  # - nix build -j0 "${FLAKEHUB_WEB_ENDPOINT}/f/ghuser-cole/flakesrock-private/0.3.1.tar.gz#truth"
  # - nix build -j0 "${FLAKEHUB_WEB_ENDPOINT}/f/ghuser-cole/flakesrock-private/*.tar.gz#truth"

  # run flakehub-push
  # - NOTE(colemickens): not sure why this got re-wrapped in bash -c ...
  - bash -c "env RUST_LOG=debug ${TMPDIR}/flakehub-push --visibility public --github-token 'THISISNOTUSED' --repository 'colemickens/flakesrock' --rolling --rolling-minor 104"
