name: Release

on:
  push:

  
jobs:
  flakehub:
    runs-on: ubuntu-22.04

    permissions:
      id-token: write # Necessary for authenticating against FlakeHub
      contents: read
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: actions/checkout@v4
      - name: Push to flakehub
        uses: determinatesystems/flakehub-push@main
        with:
          visibility: "public"
          rolling: true
          host: "https://api.flakehub.aws-test.f.second.systems" # composite action, overrides env vars, ew ugh wtf
